export const LANGUAGES = [
  { code: 'EN-US', name: 'English' },
  { code: 'ES', name: 'Spanish' },
  { code: 'FR', name: 'French' },
  { code: 'DE', name: 'German' },
  { code: 'IT', name: 'Italian' },
  { code: 'PT-PT', name: 'Portuguese' },
  { code: 'NL', name: 'Dutch' },
  { code: 'PL', name: 'Polish' },
  { code: 'RU', name: 'Russian' },
  { code: 'JA', name: 'Japanese' },
  { code: 'ZH', name: 'Chinese' },
  { code: 'KO', name: 'Korean' },
  { code: 'SV', name: 'Swedish' },
  { code: 'DA', name: 'Danish' },
  { code: 'FI', name: 'Finnish' },
  { code: 'NO', name: 'Norwegian' },
  { code: 'CS', name: 'Czech' },
  { code: 'EL', name: 'Greek' },
  { code: 'HU', name: 'Hungarian' },
  { code: 'RO', name: 'Romanian' },
  { code: 'SK', name: 'Slovak' },
  { code: 'BG', name: 'Bulgarian' },
  { code: 'TR', name: 'Turkish' },
  { code: 'ID', name: 'Indonesian' },
  { code: 'UK', name: 'Ukrainian' },
] as const;
